/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ZenInput {
  constructor()
  startPolling(callback: (err: Error | null, arg: string) => any): void
}
export declare class ZenTerminal {
  constructor()
  enableRawMode(): void
  disableRawMode(): void
  getSize(): Array<number>
}
export declare class ZenBuffer {
  constructor(width: number, height: number)
  setCell(x: number, y: number, content: string, fg?: string | undefined | null, bg?: string | undefined | null, bold?: boolean | undefined | null): void
  flush(): void
  clear(): void
  resize(width: number, height: number): void
  getWidth(): number
  getHeight(): number
}
export declare class ZenGit {
  constructor()
  getLog(limit: number): string
  getDiff(hash: string): string
  stageFile(path: string): void
  unstageFile(path: string): void
  getStatus(): string
  commit(message: string): void
  getBranches(): string
}
